
import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowRight, ArrowUpRight, Bell, CalendarDays, Check, ChevronRight, Download, Droplets, FileText, LayoutDashboard, Plus, Search, Settings, ShieldCheck, Stethoscope, TrendingUp, X, Footprints } from 'lucide-react';
import { MedicalOverview, HeartPage, AnatomyPage } from './health/MedicalOverview';
import { DailyJournal } from './health/Movement';
import './premium.css';
import { useWellness } from './health/WellnessProvider';
import { useAuth } from './health/Auth';
import { Movement } from './health/Movement';
import { HealthAccount, CloudRecords } from './health/CloudRecords';

const nav = [{name:'Overview',icon:LayoutDashboard},{name:'Movement',icon:Footprints},{name:'My body',icon:Activity},{name:'Health trends',icon:TrendingUp},{name:'Appointments',icon:CalendarDays},{name:'Health reports',icon:FileText}];
const doctors=[{name:'Dr. Richard Evans',role:'Cardiologist',time:'09:30 AM',color:'sage'},{name:'Dr. Olivia Smith',role:'Nutritionist',time:'11:00 AM',color:'pink'}];
const today=()=>new Date().toLocaleDateString('en-CA');
function read<T,>(key:string,fallback:T):T {try{return JSON.parse(localStorage.getItem('rest-'+key)||'null')??fallback;}catch{return fallback;}}
function save(key:string,value:unknown){try{localStorage.setItem('rest-'+key,JSON.stringify(value));}catch{}}
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export default function App(){
const health=useWellness(),auth=useAuth();
const water=health.today.water,checkin=health.today.checkin,setCheckin=health.setCheckin;
const displayName=auth.session?auth.name:'Your profile';
const initials=auth.session?auth.name.split(' ').map((s:string)=>s[0]).slice(0,2).join(''):'You';
const [tab,setTab]=useState('Overview'),[modal,setModal]=useState<string|null>(null),[mood,setMood]=useState('Good'),[sleep,setSleep]=useState(7.5),[symptoms,setSymptoms]=useState<string[]>([]),[bookings,setBookings]=useState<any[]>(()=>read('bookings-'+health.scope,[])),[doctor,setDoctor]=useState(doctors[0].name),[bookingDate,setBookingDate]=useState(today()),[bookingTime,setBookingTime]=useState('09:30'),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[reminders,setReminders]=useState(()=>read('reminders-'+health.scope,true));
const dialog=useRef<HTMLDialogElement>(null);const close=()=>setModal(null);
useEffect(()=>save('bookings-'+health.scope,bookings),[bookings]);useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer);},[notice]);useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
useEffect(()=>{if(modal==='checkin'){setMood(checkin?.mood??'Good');setSleep(checkin?.sleep??7.5);setSymptoms(checkin?.symptoms??[]);}},[modal]);
const navigate=(name:string)=>{setTab(name);setQuery('')};
return <div className="health-app">
<aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('Overview')}}><span className="brand-mark"><Activity size={24}/></span>rest<span className="brand-dot">.</span></a><span className="sidebar-label">YOUR PERSONAL HEALTH SPACE</span><nav>{nav.map(item=><button className={'nav-item '+(tab===item.name?'active':'')} onClick={()=>navigate(item.name)} key={item.name}><item.icon size={19}/><span>{item.name==='Health trends'?'Heart rate':item.name==='My body'?'Anatomy':item.name}</span>{tab===item.name&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="care-note"><span className="little-star">✳</span><h3>A little care.<br/>A better you.</h3><p>Small steps today.<br/>A healthier tomorrow.</p><button onClick={()=>setModal('plan')}>Explore your plan <ArrowUpRight size={16}/></button></div><button className={'nav-item '+(tab==='Settings'?'active':'')} onClick={()=>navigate('Settings')}><Settings size={19}/>Settings</button><div className="sidebar-profile"><span className="avatar">{initials}</span><div><strong>{displayName}</strong><small>Personal account</small></div><ShieldCheck size={17}/></div></div></aside>
<div className="workspace"><header className="topbar"><div className="breadcrumb">My health <ChevronRight size={13}/><span>{tab==='Health trends'?'Heart rate':tab==='My body'?'Anatomy':tab}</span></div><div className="topbar-actions"><div className="search-wrap"><Search size={17}/><input aria-label="Search health pages" placeholder="Search anything…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<div className="search-results">{nav.filter(n=>n.name.toLowerCase().includes(query.toLowerCase())).map(n=><button key={n.name} onClick={()=>navigate(n.name)}>{n.name}<ArrowUpRight size={14}/></button>)}{!nav.some(n=>n.name.toLowerCase().includes(query.toLowerCase()))&&<p>No pages found. Try “health”.</p>}</div>}</div><button className="notification-button" aria-label="Notifications" onClick={()=>setModal('notifications')}><Bell size={19}/><i/></button><button className="avatar small" aria-label="Account settings" onClick={()=>navigate('Settings')}>{initials}</button></div></header>
<main><section className="page-heading"><div><div className="eyebrow"><span/> YOUR PERSONAL HEALTH SPACE</div><h1>{tab==='Overview'?<>Your health.<br/><span>A clearer picture.</span></>:tab==='Health trends'?'Your heart, in focus.':tab==='My body'?'The human picture.':tab}</h1><p>{tab==='Overview'?'Here’s how you’re doing today. Every little step counts.':'Your personal health, thoughtfully brought together.'}</p></div><div className="heading-actions"><span className="date-label"><CalendarDays size={16}/>{new Date().toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span><button className="primary-button" onClick={()=>setModal('checkin')}>{checkin?<Check size={16}/>:<Plus size={16}/>} {checkin?'Check-in complete':'Daily check-in'}</button></div></section>
{tab==='Overview'&&<MedicalOverview navigate={navigate} onCheckin={()=>setModal('checkin')}/>}
{tab==='Movement'&&<Movement/>}
{tab==='My body'&&<AnatomyPage/>}
{tab==='Health trends'&&<HeartPage/>}
{tab==='Appointments'&&<section className="panel content-panel"><div className="panel-heading"><h2>Your appointments</h2><button className="primary-button" onClick={()=>setModal('booking')}><Plus size={16}/> Book appointment</button></div><p className="muted-copy">Manage your personal appointment schedule. Bookings are saved on this device.</p>{bookings.length?bookings.map(b=><div className="booking-item" key={b.id}><span className="doctor-avatar sage"><Stethoscope/></span><div><h3>{b.doctor}</h3><p>{b.date} at {b.time}</p><small>Personal calendar entry</small></div><button className="outline-button" onClick={()=>{setBookings(bookings.filter(x=>x.id!==b.id));setNotice('Appointment removed from your calendar.')}}>Cancel</button></div>):<div className="empty-state"><CalendarDays size={40}/><h3>A little time for your health.</h3><p>No appointments yet. Add your next consultation to your schedule.</p></div>}</section>}
{tab==='Health reports'&&<CloudRecords/>}
{tab==='Health reports'&&<DailyJournal/>}
{tab==='Settings'&&<HealthAccount/>}
{tab==='Settings'&&<section className="panel content-panel"><h2>Your space. Your preferences.</h2><div className="setting-row"><div><strong>Daily reminder preference</strong><p className="muted-copy">Save your preference for future reminders.</p></div><button className={'toggle '+(reminders?'on':'')} role="switch" aria-checked={reminders} aria-label="Daily reminder preference" onClick={()=>{setReminders(!reminders);save('reminders-'+health.scope,!reminders)}}><span/></button></div><div className="setting-row"><div><strong>Your wellness data</strong><p className="muted-copy">Steps, check-ins and workouts sync when signed in. Appointments stay in this browser.</p></div><button className="outline-button" onClick={()=>download('rest-personal-data.json',{checkin,waterMl:water,bookings,reminders,history:health.history,workouts:health.workouts})}><Download size={15}/>Export data</button></div><div className="setting-row"><div><strong>Connected devices</strong><p className="muted-copy">Connect a compatible Bluetooth heart-rate monitor.</p></div><button className="outline-button" onClick={()=>navigate('Health trends')}>Connect monitor</button></div></section>}
<footer className="page-footer"><span><span className="brand-tiny">✳</span> Thoughtfully made for a healthier you.</span><span><ShieldCheck size={13}/> Private by design <i/> Your data. Your control.</span></footer></main></div>
<dialog ref={dialog} className="app-dialog" aria-label="Health and wellness" onCancel={close} onClick={e=>{if(e.target===dialog.current)close()}}><div className="dialog-content"><button className="dialog-close round-button" aria-label="Close dialog" onClick={close}><X size={19}/></button>
{modal==='checkin'&&<form onSubmit={e=>{e.preventDefault();const value={mood,sleep,symptoms,date:today()};setCheckin(value);close();setNotice('Your daily check-in is saved. A little care goes a long way.')}}><span className="eyebrow">A MINUTE FOR YOURSELF</span><h2>How are you feeling?</h2><p className="muted-copy">Make a little space to check in with your body.</p><label>Your mood</label><div className="mood-options">{['Low','Okay','Good','Great'].map((m,i)=><button type="button" key={m} className={mood===m?'selected':''} onClick={()=>setMood(m)}><span>{['☁','◔','☀','✳'][i]}</span>{m}</button>)}</div><label htmlFor="sleep">Last night’s sleep <strong>{sleep} hours</strong></label><input id="sleep" type="range" min="0" max="12" step="0.5" value={sleep} onChange={e=>setSleep(+e.target.value)}/><label>Anything on your mind? <small>Optional</small></label><div className="symptom-options">{['Fatigue','Headache','Joint pain','Poor sleep','Eye strain'].map(s=><button key={s} type="button" className={symptoms.includes(s)?'selected':''} onClick={()=>setSymptoms(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}>{s}</button>)}</div><button className="primary-button full">Save my check-in <Check size={16}/></button></form>}
{modal==='booking'&&<form onSubmit={e=>{e.preventDefault();if(bookings.some(b=>b.date===bookingDate&&b.time===bookingTime)){setNotice('You already have an appointment at that time.');return;}setBookings(v=>[...v,{id:crypto.randomUUID(),doctor,date:bookingDate,time:bookingTime}]);close();setNotice('Appointment added to your personal calendar.')}}><span className="eyebrow">MAKE TIME FOR YOU</span><h2>Plan your next visit.</h2><p className="muted-copy">Add a personal reminder. Confirm availability directly with your clinic.</p><label htmlFor="doctor">Specialist</label><select id="doctor" value={doctor} onChange={e=>setDoctor(e.target.value)}>{doctors.map(d=><option key={d.name}>{d.name}</option>)}</select><label htmlFor="date">Date</label><input id="date" type="date" required min={today()} value={bookingDate} onChange={e=>setBookingDate(e.target.value)}/><label htmlFor="time">Time</label><input id="time" type="time" required value={bookingTime} onChange={e=>setBookingTime(e.target.value)}/><button className="primary-button full">Add to my schedule <ArrowRight size={16}/></button></form>}
{modal==='plan'&&<><span className="eyebrow">YOUR WELLNESS PLAN</span><h2>Good habits. At your pace.</h2><p className="muted-copy">Your daily checklist for a little more balance.</p>{[['A moment to check in',!!checkin],['Drink 2 liters of water',water>=2000],['Move toward 8,000 steps',health.today.steps>=8000],['Make time to wind down',false]].map(([name,done])=><div className="setting-row" key={String(name)}><span>{name}</span>{done?<Check size={18} color="#477859"/>:<span className="pill">In progress</span>}</div>)}<button className="primary-button full" onClick={()=>setModal('checkin')}>Take your daily check-in <ArrowRight size={16}/></button></>}
{modal==='notifications'&&<><span className="eyebrow">YOUR UPDATES</span><h2>A gentle reminder.</h2><div className="setting-row"><Droplets/><p>{water>=2000?'You reached your hydration goal today.':'There’s always time for a glass of water.'}</p></div><div className="setting-row"><CalendarDays/><p>{bookings.length?`${bookings.length} appointment(s) in your personal schedule.`:'Your schedule is clear. Make some time for yourself.'}</p></div><button className="primary-button full" onClick={()=>setModal('checkin')}>{checkin?'Review your check-in':'Check in with yourself'}</button></>}
</div></dialog>{notice&&<div className="toast" role="status"><Check size={18}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={15}/></button></div>}</div>;
}
