import { useState } from 'react';
import { Activity, ArrowRight, ArrowUpRight, Bluetooth, CalendarDays, Check, ChevronRight, Droplets, FileText, Flame, Footprints, Heart, Maximize2, Minus, Moon, Plus, ShieldCheck, Wind } from 'lucide-react';
import lungs from '@/assets/lungs-premium.png';
import body from '@/imports/image.png';
import { useWellness } from './WellnessProvider';
import { useHeart } from './HeartMonitor';
import { DotGraph, DotNumber, PulseOrb } from './MedicalGraphics';
import { Walker } from './Walker';

export function MedicalOverview({navigate,onCheckin}:{navigate:(name:string)=>void;onCheckin:()=>void}){
 const health=useWellness(),heart=useHeart();
 return <div className="medical-overview"><section className="organ-hero"><div className="organ-heading"><div><span className="med-kicker">THE HUMAN PICTURE</span><h2>Made to understand<br/><strong>you better.</strong></h2></div><button className="med-circle" aria-label="Explore anatomy" onClick={()=>navigate('My body')}><Maximize2 size={17}/></button></div><div className="lung-stage"><img src={lungs} alt="Three-dimensional illustration of blue lungs with pulmonary vessels and trachea"/><div className="organ-orbit"/><button className="organ-tag" onClick={()=>navigate('My body')}><span><Wind size={17}/></span> Respiratory system <ArrowUpRight size={13}/></button><button className="organ-point point-left" aria-label="Explore lung structure" onClick={()=>navigate('My body')}/><button className="organ-point point-right" aria-label="Explore respiratory system" onClick={()=>navigate('My body')}/><div className="organ-glass"><span>YOUR BODY, CONNECTED</span><Heart size={17}/><strong>A closer look.<br/>A clearer picture.</strong><button onClick={()=>navigate('My body')}>Explore your anatomy <ArrowRight size={14}/></button></div></div><div className="organ-bottom"><span><ShieldCheck size={15}/> Anatomy made simple</span><button onClick={()=>navigate('My body')}>Explore <ArrowUpRight size={16}/></button></div></section>
 <section className="med-heart-card"><div className="med-card-heading"><span><Heart size={17}/> Heart health</span><button className="med-circle" aria-label="Open heart-rate monitor" onClick={()=>navigate('Health trends')}><ArrowUpRight size={17}/></button></div><div className="med-heart-reading"><div><span>{heart.latest?'LIVE HEART RATE':'YOUR NEXT HEARTBEAT'}</span><DotNumber value={heart.latest?.bpm??null}/><small>{heart.latest?'bpm · from your monitor':'Connect. Measure. Understand.'}</small></div><div className={'red-heart-icon '+(heart.latest?'beating':'')}><Heart size={37} strokeWidth={1.1}/><span/></div></div><DotGraph values={heart.points.map(p=>p.bpm)} dark/><div className="med-heart-footer"><span><i className={heart.connected?'connected':''}/>{heart.latest?'Live sensor data':heart.connected?'Waiting for signal':'No monitor connected'}</span><button onClick={()=>navigate('Health trends')}>{heart.connected?'View session':'Connect monitor'} <ArrowRight size={14}/></button></div></section>
 <section className="med-movement-card"><div className="med-card-heading"><span><Footprints size={17}/> Your movement</span><button className="med-circle" aria-label="Open step tracking" onClick={()=>navigate('Movement')}><ArrowUpRight size={17}/></button></div><div className="med-movement-content"><div><strong>{health.today.steps.toLocaleString()}</strong><small>steps today <span>/ 8,000</span></small><div className="med-progress"><span style={{width:Math.min(100,health.today.steps/80)+'%'}}/></div><p>{health.sensor.walking?'In your rhythm.':health.sensor.tracking?'A moment of stillness.':'Find your everyday rhythm.'}</p></div><Walker moving={health.sensor.walking} scene="studio" compact/></div><button className="med-text-link" onClick={()=>navigate('Movement')}>{health.sensor.tracking?'Tracking your movement':'Start your first steps'}<ArrowRight size={15}/></button></section>
 <section className="med-daily-card"><div className="med-card-heading"><span>Little things. Better days.</span><span className="med-streak"><Flame size={15}/>{health.streak} day streak</span></div><div className="med-daily-grid"><div><span className="med-soft-icon water"><Droplets size={19}/></span><small>Hydration</small><strong>{(health.today.water/1000).toFixed(2).replace(/0$/,'')}<em>L</em></strong><button onClick={()=>health.setWater(v=>Math.min(2000,v+250))} disabled={health.today.water>=2000}>{health.today.water>=2000?<Check size={13}/>:<Plus size={13}/>} {health.today.water>=2000?'Goal reached':'250 ml'}</button></div><div><span className="med-soft-icon sleep"><Moon size={19}/></span><small>Sleep</small><strong>{health.today.checkin?.sleep??'—'}<em>h</em></strong><button onClick={onCheckin}>{health.today.checkin?'Your check-in':'Log last night'}<ChevronRight size={13}/></button></div><div><span className="med-soft-icon workout"><Activity size={19}/></span><small>Workout</small><strong>{Math.floor(health.workouts.filter(w=>w.date===health.day).reduce((n,w)=>n+w.seconds,0)/60)}<em>min</em></strong><button onClick={()=>navigate('Movement')}>Make time <ChevronRight size={13}/></button></div></div></section>
 <section className="med-next-card"><span className="med-kicker">CARE, ON YOUR TERMS</span><h2>A little time for<br/><span>yourself.</span></h2><div><button onClick={()=>navigate('Appointments')}><span className="med-soft-icon"><CalendarDays size={19}/></span><span>Plan your next visit<small>Your personal care calendar</small></span><ArrowUpRight size={18}/></button><button onClick={()=>navigate('Health reports')}><span className="med-soft-icon"><FileText size={19}/></span><span>Your health library<small>Records, reports & daily progress</small></span><ArrowUpRight size={18}/></button></div></section></div>;
}

export function HeartPage(){
 const heart=useHeart(),health=useWellness();
 const [range,setRange]=useState<'Today'|'7 days'>('Today');
 const cutoff=new Date();cutoff.setDate(cutoff.getDate()-6);cutoff.setHours(0,0,0,0);
 const records=(range==='Today'?health.today.heart:health.history.flatMap(d=>d.heart).filter(p=>p.at>=cutoff.getTime())).slice().sort((a,b)=>a.at-b.at);
 return <div className="heart-page"><section className="live-monitor"><div className="med-card-heading"><span><Heart size={17}/> Your heart. In real time.</span><Bluetooth size={20}/></div><PulseOrb active={!!heart.latest}><DotNumber value={heart.latest?.bpm??null}/><span>{heart.latest?'beats per minute':'READY WHEN YOU ARE'}</span></PulseOrb><h2>{heart.latest?'In sync with you.':'Meet your heartbeat.'}</h2><p className="monitor-status" role="status">{heart.status}</p><button className="monitor-connect" disabled={heart.connecting} onClick={heart.connected?heart.disconnect:heart.connect}><span>{heart.connected?<span className="stop-square"/>:<Bluetooth size={19}/>}</span>{heart.connecting?'Connecting…':heart.connected?'Stop session':'Connect heart monitor'}<ChevronRight size={19}/></button><small>Actual Bluetooth readings. No simulated measurements.</small></section><section className="heart-records-panel"><div className="med-card-heading"><div><span className="med-kicker">A CLEARER VIEW</span><h2>Your heart-rate history</h2></div></div><div className="movement-tabs">{(['Today','7 days'] as const).map(r=><button className={range===r?'selected':''} key={r} onClick={()=>setRange(r)}>{r}</button>)}</div><DotGraph values={records.map(p=>p.bpm)}/><div className="heart-history-stats"><div><small>Latest recorded</small><strong>{records.at(-1)?.bpm??'—'}<span>bpm</span></strong></div><div><small>Recorded average</small><strong>{records.length?Math.round(records.reduce((n,p)=>n+p.bpm,0)/records.length):'—'}<span>bpm</span></strong></div></div>{records.length?<div className="heart-reading-list">{records.slice(-8).reverse().map(p=><div key={p.at}><Heart size={15}/><span>{new Date(p.at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}<small>{p.device}</small></span><strong>{p.bpm} <small>bpm</small></strong></div>)}</div>:<div className="heart-empty"><Activity size={27}/><h3>Your first reading awaits.</h3><p>Connect a monitor that broadcasts the standard Bluetooth Heart Rate Service. Your session will appear here.</p></div>}<div className="heart-facts"><ShieldCheck size={17}/><p>These are heart-rate readings, not an ECG or a rhythm diagnosis. Compatible Android/desktop browsers can connect to supported monitors; iPhone Safari cannot. Oxygen and blood pressure require separate hardware and are not inferred from your pulse.</p></div></section></div>;
}

export function AnatomyPage(){
 const [view,setView]=useState<'lungs'|'body'>('lungs'),[zoom,setZoom]=useState(1),[part,setPart]=useState('Lungs');
 const info:Record<string,string>={Lungs:'Explore the branching structure of your respiratory system. This anatomical illustration shows lung tissue, the airways and pulmonary vessels.',Airways:'The trachea branches into bronchi, which carry air through the lungs.',Vessels:'The branching vessels connect the lungs with the heart. This illustration helps you explore their structure.'};
 return <div className="anatomy-page"><section className="anatomy-large"><div className="organ-heading"><div><span className="med-kicker">ANATOMY, UNDERSTOOD</span><h2>A closer look at<br/><strong>what makes you, you.</strong></h2></div><div className="zoom-controls"><button aria-label="Zoom in" className="med-circle" onClick={()=>setZoom(v=>Math.min(1.5,v+.1))}><Plus size={17}/></button><button aria-label="Zoom out" className="med-circle" onClick={()=>setZoom(v=>Math.max(.7,v-.1))}><Minus size={17}/></button></div></div><div className="anatomy-switch"><button className={view==='lungs'?'selected':''} onClick={()=>{setView('lungs');setZoom(1)}}>Respiratory</button><button className={view==='body'?'selected':''} onClick={()=>{setView('body');setZoom(1)}}>Full body</button></div><div className="anatomy-image-stage"><img src={view==='lungs'?lungs:body} alt={view==='lungs'?'Detailed blue lungs anatomy illustration':'Full body anatomical illustration'} style={{transform:`scale(${zoom})`}}/>{view==='lungs'&&<><button className="organ-point airways" aria-label="Learn about airways" onClick={()=>setPart('Airways')}/><button className="organ-point vessels" aria-label="Learn about pulmonary vessels" onClick={()=>setPart('Vessels')}/><button className="organ-point tissue" aria-label="Learn about lungs" onClick={()=>setPart('Lungs')}/></>}</div><div className="anatomy-caption-bottom"><span>ANTERIOR VIEW</span><span>Tap a marker to explore <Plus size={12}/></span></div></section><section className="anatomy-explain"><span className="med-soft-icon water"><Wind size={26}/></span><span className="med-kicker">YOUR BODY IN FOCUS</span><h2>{view==='body'?'The human body':part}</h2><p>{view==='body'?'Explore the relationship between the organs, muscles and skeleton in this anatomical illustration.':info[part]}</p><div className="anatomy-reading"><span>Blood oxygen</span><strong>— <small>SpO₂</small></strong><p>No oximeter connected. A phone motion sensor cannot measure blood oxygen.</p></div><div className="anatomy-reading"><span>Blood pressure</span><strong>— <small>mmHg</small></strong><p>No blood-pressure cuff connected. No estimated values are shown.</p></div><small>Illustration for visual exploration, not a scan of your body.</small></section></div>;
}
