import { useEffect, useState } from 'react';
import { ArrowUpRight, Check, Cloud, Download, Dumbbell, Flame, Footprints, Pause, Play, Smartphone, Timer, X } from 'lucide-react';
import { dateKey, type Workout } from '@/lib/wellness';
import { useWellness } from './WellnessProvider';
import { Walker, type Scene } from './Walker';

export function MovementSummary({onOpen}:{onOpen:()=>void}){
  const health=useWellness();
  return <section className="movement-summary"><div className="summary-walker"><Walker moving={health.sensor.walking} compact/></div><div><span className="eyebrow">EVERY STEP COUNTS</span><h3>{health.today.steps.toLocaleString()} <small>steps today</small></h3><p>{health.sensor.walking?'You’re moving. Keep your rhythm.':health.sensor.tracking?'Standing still. Ready for your next step.':'A fresh day. A little movement.'}</p></div><div className="summary-streak"><Flame size={21}/><strong>{health.streak}</strong><span>day streak</span></div><button className="primary-button" onClick={onOpen}>Your movement <ArrowUpRight size={15}/></button></section>;
}

export function Movement(){
  const health=useWellness();
  const [view,setView]=useState('Steps'),[scene,setScene]=useState<Scene>('garden');
  const progress=Math.min(100,Math.round(health.today.steps/8000*100));
  return <div className="movement-page"><div className="movement-toolbar"><div className="movement-tabs">{['Steps','Workouts','Daily journal'].map(v=><button key={v} className={view===v?'selected':''} onClick={()=>setView(v)}>{v}</button>)}</div><span className="sync-label" role="status" aria-live="polite"><Cloud size={14}/>{health.syncStatus}</span></div>{health.storageError&&<p role="alert" className="health-error">{health.storageError}</p>}
  {view==='Steps'&&<><div className="movement-grid"><section className="step-scene-card"><div className="panel-heading"><span className="eyebrow">YOUR DAILY MOVEMENT</span><span className={'motion-badge '+(health.sensor.walking?'moving':'')}>{health.sensor.walking?'Walking':health.sensor.tracking?'Standing still':'Sensor paused'}</span></div><div className="step-total"><strong>{health.today.steps.toLocaleString()}</strong><span>/ 8,000 steps</span></div><Walker moving={health.sensor.walking} scene={scene}/><div className="scene-switcher" aria-label="Walking scene">{(['garden','coast','studio'] as Scene[]).map(s=><button aria-pressed={scene===s} className={scene===s?'selected':''} onClick={()=>setScene(s)} key={s}><span className={'scene-swatch '+s}/>{s=== 'garden'?'Quiet garden':s==='coast'?'By the coast':'Calm studio'}</button>)}</div><div className="goal-progress"><span style={{width:progress+'%'}}/></div><div className="goal-caption"><span>{progress}% of your daily goal</span><span>Little steps. Lasting change.</span></div></section><div className="movement-side"><section className="panel sensor-panel"><span className="sensor-icon"><Smartphone size={24}/></span><h2>Move at your own pace.</h2><p>Carry your phone in your pocket. We’ll count your steps and your companion will follow along.</p><div className="sensor-status" role="status"><span className={health.sensor.tracking?'green-dot':''}/>{health.sensor.message}</div><button className="primary-button full" disabled={health.sensor.requesting} onClick={health.sensor.tracking?health.sensor.stop:health.sensor.start}>{health.sensor.tracking?<Pause size={16}/>:<Play size={16}/>} {health.sensor.requesting?'Requesting access…':health.sensor.tracking?'Pause tracking':'Start tracking'}</button><small>Keep this page open and your screen awake. Browser sensors estimate steps; they cannot count while the app is closed.</small></section><section className="streak-card"><Flame size={25}/><div><strong>{health.streak}<span> day wellness streak</span></strong><p>A check-in, 100 steps, or a little hydration keeps it going.</p></div></section><section className="panel movement-tip"><span className="eyebrow">YOUR DAILY BALANCE</span><div><DropletIcon/><strong>{health.today.water/1000} L</strong><span>water today</span></div><div><Timer size={19}/><strong>{Math.floor(health.workouts.filter(w=>w.date===health.day).reduce((n,w)=>n+w.seconds,0)/60)} min</strong><span>workouts today</span></div></section></div></div><p className="movement-footnote">The character reacts to detected steps and returns to standing after a short pause. Sensor access depends on your phone and browser. Count on one device at a time to avoid overlapping totals.</p></>}
  {view==='Workouts'&&<Workouts/>}{view==='Daily journal'&&<DailyJournal/>}</div>;
}
function DropletIcon(){return <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M12 3S5 11 5 15a7 7 0 0 0 14 0c0-4-7-12-7-12Z"/></svg>}
type Draft={id:string;type:string;elapsed:number;runningSince:number|null;stepStart:number;stepAccum?:number};
function Workouts(){
  const health=useWellness(),key='rest-workout-draft-'+health.scope;
  const [type,setType]=useState('Walking');
  const [draft,setDraft]=useState<Draft|null>(()=>{try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}});
  const [now,setNow]=useState(Date.now()),[message,setMessage]=useState('');
  const totalSteps=Object.values(health.journal.days).reduce((n,d)=>n+d.steps,0);
  const seconds=draft?Math.max(0,draft.elapsed+(draft.runningSince?Math.floor((now-draft.runningSince)/1000):0)):0;
  const sessionSteps=draft?Math.max(0,(draft.stepAccum||0)+(draft.runningSince?totalSteps-draft.stepStart:0)):0;
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(timer);},[]);
  useEffect(()=>{try{if(draft)localStorage.setItem(key,JSON.stringify(draft));else localStorage.removeItem(key);}catch{setMessage('Workout timer cannot be saved in this browser. Keep this page open until you finish.');}},[draft,key]);
  function finish(){
    if(!draft)return;
    if(seconds<60){setMessage('Keep going for at least one minute to save a workout.');return;}
    health.addWorkout({id:draft.id,type:draft.type,date:dateKey(),seconds,steps:sessionSteps,finishedAt:new Date().toISOString()});
    setDraft(null);setMessage('Workout saved. A little stronger, one session at a time.');
  }
  return <div className="workouts-layout"><section className="panel workout-timer-card"><span className="eyebrow">TIME FOR YOURSELF</span><h2>{draft?draft.type+' session':'Make your next move.'}</h2><p>Pick a workout. Start your timer. Celebrate showing up.</p><div className="workout-types">{['Walking','Strength','Yoga','Cycling'].map(t=><button disabled={!!draft} key={t} aria-pressed={(draft?.type||type)===t} className={(draft?.type||type)===t?'selected':''} onClick={()=>setType(t)}>{t}</button>)}</div><div className="workout-clock"><span><Timer size={19}/>{draft?.runningSince?'Session in progress':draft?'Paused':'Ready when you are'}</span><strong>{String(Math.floor(seconds/3600)).padStart(2,'0')}:{String(Math.floor(seconds/60)%60).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong><small>{sessionSteps} sensor steps during this session</small></div><div className="workout-actions">{!draft?<button className="primary-button" onClick={()=>{setNow(Date.now());setMessage('');setDraft({id:crypto.randomUUID(),type,elapsed:0,runningSince:Date.now(),stepStart:totalSteps});}}><Play size={15}/> Start workout</button>:<><button className="outline-button" onClick={()=>{setNow(Date.now());setDraft({...draft,elapsed:seconds,stepAccum:sessionSteps,stepStart:totalSteps,runningSince:draft.runningSince?null:Date.now()});}}>{draft.runningSince?<Pause size={15}/>:<Play size={15}/>} {draft.runningSince?'Pause':'Resume'}</button><button className="primary-button" onClick={finish}><Check size={15}/> Finish & save</button></>}</div>{draft&&<button className="discard-workout" onClick={()=>{setDraft(null);setMessage('Session discarded. Your daily steps are unchanged.');}}>Discard session</button>}{message&&<p className="workout-message" role="status">{message}</p>}<p className="movement-footnote">Start the motion sensor in Steps to include detected movement. The timer also supports workouts without a sensor. Sessions are recorded on the day you finish.</p></section><section className="panel workout-history"><div className="panel-heading"><h2>Your workouts</h2><span className="pill"><Flame size={13}/> {health.workoutStreak} day streak</span></div>{!health.workouts.length?<div className="empty-state"><Dumbbell size={35}/><h3>Your first session awaits.</h3><p>Completed workouts appear here and in your daily journal.</p></div>:health.workouts.map(w=><div className="workout-record" key={w.id}><span className="report-icon"><Dumbbell size={19}/></span><div><strong>{w.type}</strong><small>{w.date} · {Math.floor(w.seconds/60)} min {w.seconds%60}s</small></div><span>{w.steps.toLocaleString()} steps</span></div>)}</section></div>;
}
export function DailyJournal(){
  const health=useWellness();
  function exportHistory(){const url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),dailyHistory:health.history},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='rest-daily-history.json';a.click();URL.revokeObjectURL(url);}
  return <section className="panel journal-panel"><div className="panel-heading"><div><span className="eyebrow">YOUR STORY, DAY BY DAY</span><h2>A record of showing up.</h2></div><button className="outline-button" onClick={exportHistory}><Download size={15}/> Export history</button></div>{!health.history.length?<div className="empty-state"><Footprints size={35}/><h3>Your journey starts today.</h3><p>Take a few steps, log water, finish a workout, or save your daily check-in.</p></div>:<div className="journal-table-wrap"><table><thead><tr><th>Day</th><th>Steps</th><th>Water</th><th>Sleep</th><th>Mood</th><th>Workouts</th></tr></thead><tbody>{health.history.map(d=><tr key={d.date}><td>{new Date(d.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}{d.date===health.day&&<small>Today</small>}</td><td>{d.steps.toLocaleString()}</td><td>{d.water/1000} L</td><td>{d.checkin?`${d.checkin.sleep} h`:'—'}</td><td>{d.checkin?.mood||'—'}</td><td>{d.workouts.length?`${d.workouts.length} · ${Math.floor(d.workouts.reduce((n,w)=>n+w.seconds,0)/60)} min`:'—'}</td></tr>)}</tbody></table></div>}<p className="movement-footnote">Daily records use your local calendar day. Your wellness streak stays active if you logged activity today or yesterday; workout streaks require a completed session of at least one minute.</p></section>;
}
